version: "3.7"
services:

  list-msg-flask:
    build: .
    container_name: list-msg-flask
    restart: always
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  redis:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]